controller:
  serviceType: LoadBalancer
  image:
    tag: "2.492.1-jdk21"
  admin:
    username: admin
    password: admin123

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - amazon-ecr:latest
    - pipeline-aws:latest
    - docker-workflow:latest
    - credentials-binding:latest
    - job-dsl:latest

  JCasC:
    configScripts:
      pipeline-job: |
        jobs:
          - script: >
              pipelineJob('django-ci-cd') {
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/kulik-dari/devops-hw3')
                          branch('*/lesson-8-9')
                        }
                      }
                    }
                    scriptPath('lesson-8-9/Jenkinsfile')
                  }
                }
              }

agent:
  enabled: true
  namespace: jenkins
  podTemplates:
    kaniko: |
      - name: kaniko
        label: kaniko
        containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            command: /busybox/cat
            ttyEnabled: true
          - name: git
            image: alpine/git:latest
            command: cat
            ttyEnabled: true

persistence:
  enabled: true
  size: 10Gi
