image:
  repository: 746764748053.dkr.ecr.us-west-2.amazonaws.com/lesson-7-django
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

replicaCount: 2

autoscaler:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

config:
  DJANGO_SETTINGS_MODULE: "myproject.settings"
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "django_user"
  POSTGRES_PASSWORD: "pass9764gd"
